### PR TITLE
Feature authentication

### PR DESCRIPTION
**Pull request by ashishk-globant**
Implemented the authentication functionality in Classifieds server application(to be integrated with client app)

### CODE REVIEW

**Comment by santoshkale3** [comment]
You have created incorrect pull request to merge commits into master.
please create a pull request to merge commits into Dev1.0 from your Feature branch.

**Comment by ashishk-globant** [comment]
Edited the pull request and assigned back to you.

**Comment by santoshkale3** [comment]
This branch has conflicts that must be resolved
Please resolve all conflicts first.

**Review by santoshkale3 — CHANGES_REQUESTED** [review]
This branch has conflicts that must be resolved

**Pull request closed without merging**
