### PR TITLE
Feature authentication

### PR DESCRIPTION
**Pull request by ashishk-globant**
Resolved the conflicts in addition to implementation of authentication & user service

### CODE REVIEW

**Review by santoshkale3 — CHANGES_REQUESTED** [review]
[ReviewComments_Classifieds.xlsx](https://github.com/globant-ui/classifieds/files/710735/ReviewComments_Classifieds.xlsx)
please find attached review comments for user service

**Comment by santoshkale3** [comment]
please find review comments for User Authentication.
[ReviewComments_Classifieds.xlsx](https://github.com/globant-ui/classifieds/files/710947/ReviewComments_Classifieds.xlsx)

**Comment by santoshkale3** [comment]
There are no test cases for CommonDBRepository.cs

**Comment by ashishk-globant** [comment]
Addressed the review comments.

**Pull request closed without merging**
